name: Docker Development Environment

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-docker-environment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build development environment
      run: |
        docker-compose up --build -d

    - name: Test Monaco Editor installation
      run: |
        docker-compose exec -T typescript-learning npm install monaco-editor

    - name: Test application startup
      run: |
        timeout 30 bash -c 'until curl -f http://localhost:3000; do sleep 2; done'

    - name: Cleanup
      run: |
        docker-compose down -v
